[package]
name = "aggregator-simple"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
alloy-primitives = { workspace = true }
wit-bindgen-rt = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
wavs-wasi-utils = { workspace = true }
wstd = { workspace = true }
alloy-network = { workspace = true }
alloy-provider = { workspace = true }
wavs-types = { workspace = true }
wit-bindgen = { workspace = true }
wasip2 = { workspace = true }
