[default]
log_level = ["debug"]

# Those configs are global and shared between wavs and aggregator
jaeger = "http://localhost:4317"
prometheus = "http://localhost:9090"


# ----------------------------
# Chain configurations
# ----------------------------

# == Ethereum chains ==

# Testnet

[default.chains.evm.11155111]
ws_endpoints = ["wss://ethereum-sepolia-rpc.publicnode.com"]
http_endpoint = "https://ethereum-sepolia-rpc.publicnode.com"

# ----------------------------
# WAVS specific settings
# ----------------------------
[wavs]
cors_allowed_origins = [
    "https://lay3rlabs.github.io/*",
    "http://localhost:*",
    "http://127.0.0.1:*",
]

dev_endpoints_enabled = true

# P2P networking for multi-operator setups
[wavs.p2p.local]
listen_port = 9000


# ----------------------------
# CLI specific settings
# ----------------------------
[cli]
# The directory to store the data.
data = "~/wavs/cli"


# ----------------------------
# Aggregator specific settings
# ----------------------------
[aggregator]
# The directory to store the data.
data = "~/wavs/aggregator"

dev_endpoints_enabled = true

cors_allowed_origins = [
    "https://lay3rlabs.github.io/*",
    "http://localhost:*",
    "http://127.0.0.1:*",
]
